version: "2"
services:
  zookeeper:
    image: "zookeeper:latest"
    ports:
      - "2181:2181"
    restart: always

  mesos-master:
    image: "mesosphere/mesos-master:1.0.11.0.1-2.0.93.ubuntu1404"
    ports:
      - "5050:5050"
    environment:
      - "MESOS_PORT=5050"
      - "MESOS_REGISTRY=in_memory"
      - "MESOS_LOG_DIR=/var/log/mesos"
      - "MESOS_WORK_DIR=/var/tmp/mesos"
      - "MESOS_QUORUM=1"
      - "MESOS_HOSTNAME=mesos-master"
      - "MESOS_ZK=zk://zookeeper:2181/mesos"
    restart: always
    depends_on:
      - zookeeper

  mesos-slave:
    image: "mesosphere/mesos-slave:1.0.11.0.1-2.0.93.ubuntu1404"
    ports:
      - "5051:5051"
    environment:
      - "MESOS_PORT=5051"
      - "MESOS_SWITCH_USER=0"
      - "MESOS_CONTAINERIZERS=docker,mesos"
      - "MESOS_LOG_DIR=/var/log/mesos"
      - "MESOS_WORK_DIR=/var/tmp/mesos"
      - "MESOS_HOSTNAME=mesos-slave"
      - "MESOS_MASTER=zk://zookeeper:2181/mesos"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    privileged: true
    depends_on:
      - mesos-master

  marathon:
    image: "mesosphere/marathon:v1.3.3"
    ports:
      - "8080:8080"
    environment:
      - "MARATHON_MASTER=zk://zookeeper:2181/mesos"
      - "MARATHON_ZK=zk://zookeeper:2181/marathon"
    restart: always
    depends_on:
      - mesos-master
      - mesos-slave

  chronos:
    image: "mesosphere/chronos:chronos-2.5.0-0.1.20160824153434.ubuntu1404-mesos-1.0.0"
    command: "/usr/bin/chronos run_jar --http_port 4400 --master zk://zookeeper:2181/mesos --zk_hosts zookeeper:2181"
    ports:
      - "4400:4400"
    restart: always
    depends_on:
      - mesos-master
      - mesos-slave

